name: dragon
on: push
jobs:
    dragon:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: permission
              run: chmod +x script.sh
            - name: run shell script
              run: ./script.sh