name: secrets
on:  push
env:
    repo: test-repo1110
    username: mikeytr07
    imagename: build-nginx
jobs:
    docker-build:
        runs-on: ubuntu-slim
        steps:
            - name: docker
              run: echo docker build -t ${{ env.repo }}/${{ vars.username }}/${{ env.imagename}}:latest
            - name: docker login
              run: echo docker login --username=${{ vars.username }} --password=${{ secrets.password }}
            - name: docker push
              run: echo docker push ${{ env.repo }}/${{ vars.username }}/${{ env.imagename}}
    docker-deploy:
        needs: docker-build
        runs-on: ubuntu-slim
        concurrency:
          group: "prod"
          cancel-in-progress: false
        steps:
            - name: deploy
              timeout-minutes: 1
              run: |
               echo docker run -p 8080:80 ${{ env.repo }}/${{ vars.username }}/${{ env.imagename}}:latest
               sleep 100